AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for E-commerce Clean Architecture

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  # Products Table
  ProductsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Environment}-products
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: categoryId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: categoryId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Categories Table
  CategoriesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Environment}-categories
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: categoryId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: categoryId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Discounts Table
  DiscountsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Environment}-discounts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: discountId
          AttributeType: S
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: discountId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ProductIndex
          KeySchema:
            - AttributeName: productId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Warehouses Table
  WarehousesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Environment}-warehouses
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: warehouseId
          AttributeType: S
        - AttributeName: location
          AttributeType: S
      KeySchema:
        - AttributeName: warehouseId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: LocationIndex
          KeySchema:
            - AttributeName: location
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Payments Table
  PaymentsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Environment}-payments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: paymentId
          AttributeType: S
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: paymentId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: OrderIndex
          KeySchema:
            - AttributeName: orderId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Shipments Table
  ShipmentsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Environment}-shipments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shipmentId
          AttributeType: S
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: warehouseId
          AttributeType: S
      KeySchema:
        - AttributeName: shipmentId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: OrderIndex
          KeySchema:
            - AttributeName: orderId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: WarehouseIndex
          KeySchema:
            - AttributeName: warehouseId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Orders Table
  OrdersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${Environment}-orders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CustomerIndex
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ProductsTableName:
    Description: Products table name
    Value: !Ref ProductsTable
    Export:
      Name: !Sub ${Environment}-products-table-name

  CategoriesTableName:
    Description: Categories table name
    Value: !Ref CategoriesTable
    Export:
      Name: !Sub ${Environment}-categories-table-name

  DiscountsTableName:
    Description: Discounts table name
    Value: !Ref DiscountsTable
    Export:
      Name: !Sub ${Environment}-discounts-table-name

  WarehousesTableName:
    Description: Warehouses table name
    Value: !Ref WarehousesTable
    Export:
      Name: !Sub ${Environment}-warehouses-table-name

  PaymentsTableName:
    Description: Payments table name
    Value: !Ref PaymentsTable
    Export:
      Name: !Sub ${Environment}-payments-table-name

  ShipmentsTableName:
    Description: Shipments table name
    Value: !Ref ShipmentsTable
    Export:
      Name: !Sub ${Environment}-shipments-table-name

  OrdersTableName:
    Description: Orders table name
    Value: !Ref OrdersTable
    Export:
      Name: !Sub ${Environment}-orders-table-name
